// Generated by https://quicktype.io
import { Product } from '../products/entities/product.entity';

export interface AllCategoriesProducts {
  categoryId: number;
  categoryName: string;
  products: Product[];
}
